-- SCHEMA FOR GREEN SEVA SUPABASE BACKEND

-- 1. Profiles Table (Extends Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  email TEXT,
  rank TEXT DEFAULT 'Eco Novice',
  total_weight DECIMAL DEFAULT 0,
  eco_points INTEGER DEFAULT 0,
  impact_progress INTEGER DEFAULT 0,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Recycling Logs Table
CREATE TABLE recycling_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL, -- e.g., 'Plastic', 'Metal'
  weight TEXT NOT NULL, -- e.g., '2.5 kg'
  points INTEGER DEFAULT 0,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Recycling Centers Table
CREATE TABLE recycling_centers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  distance TEXT,
  types TEXT[], -- Array of strings
  status TEXT, -- 'Open', 'Closing Soon'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE recycling_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE recycling_centers ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Profiles: Users can view and update their own profiles
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Recycling Logs: Users can view/create/delete their own logs
CREATE POLICY "Users can view own logs" ON recycling_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own logs" ON recycling_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own logs" ON recycling_logs FOR DELETE USING (auth.uid() = user_id);

-- Recycling Centers: Everyone can read
CREATE POLICY "Everyone can view centers" ON recycling_centers FOR SELECT USING (true);

-- TRIGGER FOR NEW USER SIGNUP
-- Automatically creates a profile when a new user signs up in Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (new.id, new.raw_user_meta_data->>'name', new.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- SEED DATA FOR CENTERS
INSERT INTO recycling_centers (name, distance, types, status)
VALUES 
('EcoCenter Central', '0.8 km', ARRAY['Plastic', 'Paper', 'Metal'], 'Open'),
('GreenHub North', '1.5 km', ARRAY['E-Waste', 'Glass'], 'Closing Soon'),
('PureCycle West', '2.3 km', ARRAY['Plastic', 'Organic'], 'Open');
